modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mod_pack_naidru_and_gamer"
version="1.0.0"
displayName="Mod Pack (Naidru and Gamer)"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="gabeh, MCreator"

[[dependencies.mod_pack_naidru_and_gamer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



